/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mystore;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NgaPC and DemTran
 */
public class TheMainScreenClient extends javax.swing.JFrame {

    /**
     * Creates new form TheMainScreenClient
     */
    private static final boolean IS_DONE = false;
    private String currentPath = null;
    private String currentFolder = null;
    private static String rootFilePath;
    private static String syncState = "chuẩn bị đồng bộ";
    private InputStream is = null;
    private OutputStream os = null;
    private static ClientInterface client;
    private static ServerInterface server;
    private static Thread syncThread;

    public TheMainScreenClient(String rootFilePath1, ClientInterface client, ServerInterface server) {
        this.rootFilePath = rootFilePath1;
        this.client = client;
        this.server = server;

        initComponents();
        loadFile(tb_file, rootFilePath1);
        loadFolder(tb_folder, rootFilePath1);
        System.out.println(rootFilePath1);
        currentPath = rootFilePath1;
        currentFolder = getParentFolder(currentPath);
        lb_currentPath.setText(currentPath);
        syncThread = null;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lb_currentPath = new javax.swing.JLabel();
        bt_back = new javax.swing.JButton();
        bt_next = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_folder = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_file = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bt_newFolder = new javax.swing.JButton();
        bt_newFile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bt_Syn = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lb_currentPath.setText("Current Path: ");

        bt_back.setText("Pre");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        bt_next.setText("Next");
        bt_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lb_currentPath, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(bt_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_next)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_currentPath, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(bt_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_next))
                .addContainerGap())
        );

        tb_folder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name Folder", "Path"
            }
        ));
        jScrollPane1.setViewportView(tb_folder);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Folder:");

        tb_file.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name File", "Length", "Created Date", "Path"
            }
        ));
        jScrollPane2.setViewportView(tb_file);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("File:");

        bt_newFolder.setText("New Folder");
        bt_newFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_newFolderActionPerformed(evt);
            }
        });

        bt_newFile.setText("Coppy File");
        bt_newFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_newFileActionPerformed(evt);
            }
        });

        jButton1.setText("newfile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_newFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bt_newFile, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_newFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_newFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        bt_Syn.setText("Start");
        bt_Syn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SynActionPerformed(evt);
            }
        });

        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_Syn, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(bt_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_Syn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// nút lùi lại
    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // TODO add your handling code here:
        currentPath = getPath(currentPath);
        currentFolder = getParentFolder(currentPath);
        lb_currentPath.setText("Current Path: " + currentPath);
        loadFolder(tb_folder, currentPath);
        loadFile(tb_file, currentPath);

    }//GEN-LAST:event_bt_backActionPerformed

    private void bt_newFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_newFolderActionPerformed
        // TODO add your handling code here:
        String folderName = JOptionPane.showInputDialog(null, "Folder name: ");
        File f;
        System.out.println(folderName);
        f = new File(currentPath + "/" + folderName);
        if (f.mkdir()) {
            loadFolder(tb_folder, currentPath);
            loadFile(tb_file, currentPath);
        } else {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra vui lòng thử lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_newFolderActionPerformed

    private void bt_newFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_newFileActionPerformed
        // TODO add your handling code here:
        JFileChooser x = new JFileChooser();
        while (true) {
            int returnvalue = x.showOpenDialog(null);
            if (returnvalue == JFileChooser.APPROVE_OPTION) {
                try {
                    String fileName = x.getSelectedFile().getName();
                    String filePath = x.getSelectedFile().getPath();
                    File f1 = new File(filePath);
                    File f2 = new File(currentPath, fileName);
                    System.out.println(currentPath);
                    // xác định đầu ra và đầu vào  để còn coppy
                    is = new FileInputStream(f1);
                    os = new FileOutputStream(f2);
                    byte[] buffer = new byte[1024];
                    int length;
                    while ((length = is.read(buffer)) > 0) {
                        os.write(buffer, 0, length);
                    }
                    is.close();
                    os.close();
                    System.out.println("Copy thành công");
                    loadFolder(tb_folder, currentPath);
                    loadFile(tb_file, currentPath);
                    break;

                } catch (Exception e) {
                    System.out.println("khong copy duoc");
                }
            } else {
                System.out.println("không coppy được");
                break;
            }
        }
    }//GEN-LAST:event_bt_newFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String folderName = JOptionPane.showInputDialog(null, "Folder name: ");
        File f;
        System.out.println(folderName);
        f = new File(currentPath + "/" + folderName);
        try {
            if (f.createNewFile()) {
                loadFolder(tb_folder, currentPath);
                loadFile(tb_file, currentPath);
            } else {

            }        // TODO add your handling code here:
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "có lỗi sảy ra vui lòng thử lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nextActionPerformed
        // TODO add your handling code here:
        int row = tb_folder.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "bạn phải chọn folder", "lỗi", JOptionPane.ERROR);
        } else {
            String driect = (String) tb_folder.getValueAt(row, 1);
            currentPath = driect;

            System.out.println(currentPath);
            currentFolder = getParentFolder(currentPath);
            lb_currentPath.setText(currentPath);
            loadFolder(tb_folder, currentPath);
            loadFile(tb_file, currentPath);

        }


    }//GEN-LAST:event_bt_nextActionPerformed

    private void bt_SynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SynActionPerformed
        // TODO add your handling code here:
        if (bt_Syn.getText().equals("Start")) {
            try {
                System.out.println("1");
                startSync();
            } catch (RemoteException ex) {

            }
            bt_Syn.setText("Stop");
        } else if (bt_Syn.getText().equals("Stop")) {
            try {
                stopSync();
            } catch (RemoteException ex) {
                Logger.getLogger(TheMainScreenClient.class.getName()).log(Level.SEVERE, null, ex);
            }
            bt_Syn.setText("Start");

        }
    }//GEN-LAST:event_bt_SynActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
        int rowfolder = tb_folder.getSelectedRow();
        int rowfile = tb_file.getSelectedRow();
        if (rowfolder < 0 && rowfile < 0) {
            JOptionPane.showMessageDialog(null,
                    "You must choose a file or folder", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            if(rowfile>=0){
                String pathDelFile=(String)tb_file.getValueAt(rowfile, 3);
                File delFile = new File(pathDelFile);
                delFile.delete();
                loadFile(tb_file, currentPath);
                loadFolder(tb_folder, currentPath);
                
            }
            if(rowfolder>=0){
                String pathDelFoder= (String)tb_folder.getValueAt(rowfolder, 1);
                File delFoder = new File(pathDelFoder);
                deleteFolder(delFoder);
                delFoder.delete();
                loadFile(tb_file, currentPath);
                loadFolder(tb_folder, currentPath);
            }
        }
    }//GEN-LAST:event_bt_deleteActionPerformed

    public void loadFolder(JTable tb, String ROOT_FILE_PATH) {
        String[] title1 = new String[2];
        title1[0] = "Folder";
        title1[1] = "Path";
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(title1);// dong nay co the bo luon

        String[] link = new String[100];
        String[] linkName = new String[100];
        String[] array = new String[100];
        int i = 0;
        File f = new File(ROOT_FILE_PATH);
        File[] allsubFiles = f.listFiles();
        for (File file : allsubFiles) {
            if (file.isDirectory()) {
                link[i] = file.getAbsolutePath();
                linkName[i] = file.getName();
                array[0] = linkName[i];
                array[1] = link[i];
                i++;
                model.addRow(array);
            }
        }
        tb.setModel(model);
    }

    public void loadFile(JTable tb, String ROOT_FILE_PATH) {
        String[] title1 = new String[4];
        title1[0] = "File name";
        title1[1] = "Length";
        title1[2] = "Date Modified";
        title1[3] = "Path";
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(title1);
        String[] fileName = new String[100];
        String[] fileType = new String[100];
        String[] array = new String[100];
        int i = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        File f = new File(ROOT_FILE_PATH);
        File[] allSubFiles = f.listFiles();
        for (File file : allSubFiles) {
            if (!file.isDirectory()) {
                Long length = file.length();
                array[0] = file.getName();
                array[1] = length.toString();
                array[2] = sdf.format(file.lastModified());
                array[3] = file.getPath();
                model.addRow(array);
            }
        }
        tb.setModel(model);

    }

    private void stopSync() throws RemoteException {
        Synchronization.stopsync();
        
        if (syncThread.isAlive()) {
            System.out.println("Waiting for thread stop...");
            while(syncThread.isAlive()) {}
            try {
                syncThread.join();
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        }
    }

    private static String getSyncState() throws RemoteException {
        if (Synchronization.getState() == 1) {
            syncState = "Uploading....";
        } else if (Synchronization.getState() == 2) {
            syncState = "Downloading....";
        } else if (Synchronization.getState() == 0) {
            syncState = "Server and client is synchronized";
        }
        return syncState;
    }

    private static void startSync() throws RemoteException {
        if (server.connect(client)) {
            File clientFile = new File(rootFilePath);
            File serverFile = server.getServerFile();
            Synchronization sync = new Synchronization(IS_DONE, clientFile, serverFile, client, server);

            syncThread = new Thread(sync);
            syncThread.start();

        }
    }
// hàm này không hiểu nó làm kiểu gì luôn coppy nguyên

    public String getParentFolder(String currentPath) {

        int beginIndex = 0;
        for (int i = currentPath.length() - 1; i >= 0; i--) {
            if ((int) currentPath.charAt(i) == 92) {
                beginIndex = i;
                break;
            }
        }
        String parentFolder = currentPath.substring(beginIndex + 1);
        return parentFolder;
    }

    // delete folder xóa hết file trước rồi xóa phần còn lại
    public boolean deleteFolder(File delFolder) {
        if (delFolder.isDirectory()) {
            if (delFolder.list().length == 0) {
                delFolder.delete();
                return true;
            } else {
                File[] allSubFiles = delFolder.listFiles();
                for (File file : allSubFiles) {
                    if (file.isDirectory()) {
                        deleteFolder(file);
                    } else {
                        file.delete();
                    }
                }
            }
        } else {
            delFolder.delete();
            return true;
        }
        return false;
    }

    // hàm này cũng không hiểu lắm
    public String getPath(String currentPath) {
        int endIndex = 0;
        for (int i = currentPath.length() - 1; i >= 0; i--) {
            if ((int) currentPath.charAt(i) == 92) {// dau /
                endIndex = i;
                break;
            }
        }
        if ((int) currentPath.charAt(endIndex - 1) == 58) {// dau :
            String checkPath = currentPath.substring(0, endIndex + 1);
            return checkPath;
        } else {
            String checkPath = currentPath.substring(0, endIndex);
            return checkPath;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheMainScreenClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheMainScreenClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheMainScreenClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheMainScreenClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Syn;
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_newFile;
    private javax.swing.JButton bt_newFolder;
    private javax.swing.JButton bt_next;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_currentPath;
    private javax.swing.JTable tb_file;
    private javax.swing.JTable tb_folder;
    // End of variables declaration//GEN-END:variables
}
